name: main

on:
  schedule:
    #  8:30 as UTC
    - cron: "30 23 * * *"
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "13.14.0"
      - run: yarn install
      - run: yarn start
        env:
          USERNAME: ${{secrets.USERNAME}}
          PASSWORD: ${{secrets.PASSWORD}}
          SLACK_INCOMING_WEB_HOOK: ${{secrets.SLACK_INCOMING_WEB_HOOK}}
          GYAZO_ACCESSTOKEN: ${{secrets.GYAZO_ACCESSTOKEN}}
